from __future__ import annotations
import re
import time

from app.llm import llm_client
from app.nodes.discovery import get_sql_tool
from app.state import AgentState
from app.tools.sql_tool import SQLValidationError

SYSTEM = """You are the SQL Agent. Given a table named `dataset` and its schema,
write ONE read-only DuckDB SQL query (SELECT or WITH only) that best answers
the business question. Respond with ONLY the SQL, no explanation, no markdown
fences."""


def _heuristic_query(question: str, columns: list[str]) -> tuple[str, str]:
    """Deterministic fallback query builder used when no live LLM is configured.
    Picks a sensible aggregate query based on keywords in the question and the
    columns actually present in the dataset. Always read-only.

    Args:
        question: The natural language business question.
        columns: List of available column names.

    Returns:
        A tuple of (SQL query, reasoning string).
    """

    q = question.lower()
    cols = set(columns)
    has = lambda c: c in cols  # noqa: E731

    date_col = (
        "order_date"
        if has("order_date")
        else next((c for c in columns if "date" in c.lower()), None)
    )
    value_col = (
        "revenue"
        if has("revenue")
        else next(
            (c for c in columns if c.lower() in ("amount", "sales", "value")), None
        )
    )

    if (
        any(k in q for k in ["trend", "over time", "forecast", "month", "quarter"])
        and date_col
        and value_col
    ):
        sql = (
            f"SELECT date_trunc('month', CAST({date_col} AS TIMESTAMP)) AS month, "
            f"SUM({value_col}) AS total_{value_col}, COUNT(*) AS order_count "
            f"FROM dataset GROUP BY 1 ORDER BY 1"
        )
        return sql, "heuristic: time-trend question detected -> monthly aggregation"

    if any(k in q for k in ["region"]) and has("region") and value_col:
        sql = (
            f"SELECT region, SUM({value_col}) AS total_{value_col}, COUNT(*) AS order_count "
            f"FROM dataset WHERE region IS NOT NULL GROUP BY region ORDER BY total_{value_col} DESC"
        )
        return sql, "heuristic: 'region' mentioned -> group by region"

    if any(k in q for k in ["category", "product"]) and has("category") and value_col:
        sql = (
            f"SELECT category, SUM({value_col}) AS total_{value_col}, COUNT(*) AS order_count, "
            f"AVG({value_col}) AS avg_{value_col} "
            f"FROM dataset GROUP BY category ORDER BY total_{value_col} DESC"
        )
        return sql, "heuristic: 'category/product' mentioned -> group by category"

    if any(k in q for k in ["channel"]) and has("channel") and value_col:
        sql = (
            f"SELECT channel, SUM({value_col}) AS total_{value_col}, COUNT(*) AS order_count "
            f"FROM dataset GROUP BY channel ORDER BY total_{value_col} DESC"
        )
        return sql, "heuristic: 'channel' mentioned -> group by channel"

    if value_col:
        sql = f"SELECT * FROM dataset ORDER BY {value_col} DESC LIMIT 200"
        return (
            sql,
            "heuristic: no specific dimension detected -> top rows by value column",
        )

    return "SELECT * FROM dataset LIMIT 200", "heuristic: generic fallback sample"


async def sql_agent_node(state: AgentState) -> AgentState:
    """Generate and execute a SQL query against the in-memory dataset.

    Args:
        state: Current agent state with ``plan``, ``schema``, ``question``, and ``dataset_source``.

    Returns:
        Updated agent state with ``sql_query``, ``sql_result``, and an appended ``trace`` entry.
    """
    t0 = time.time()
    trace = state.get("trace", [])

    if not state.get("plan", {}).get("needs_sql", True):
        trace.append(
            {
                "node": "sql_agent",
                "duration_ms": 0,
                "status": "skipped",
                "detail": "planner determined SQL was not needed",
            }
        )
        return {**state, "trace": trace}

    columns = [c["name"] for c in state["schema"]["columns"]]

    if llm_client.live:
        raw_sql = await llm_client.complete(
            SYSTEM,
            f"Question: {state['question']}\nColumns: {columns}\nTable: dataset",
            max_tokens=400,
        )
        sql = re.sub(r"^```sql|```$", "", raw_sql.strip(), flags=re.MULTILINE).strip()
        reasoning = "generated by live LLM"
    else:
        sql, reasoning = _heuristic_query(state["question"], columns)

    tool = get_sql_tool(state["dataset_source"])
    try:
        result = tool.run(sql)
        status, detail = (
            "ok",
            f"{reasoning}; {result['row_count']} rows in {result['execution_ms']}ms",
        )
    except SQLValidationError as e:
        result = {"columns": [], "rows": [], "row_count": 0, "error": str(e)}
        status, detail = "error", str(e)

    trace.append(
        {
            "node": "sql_agent",
            "duration_ms": round((time.time() - t0) * 1000, 1),
            "status": status,
            "detail": detail,
        }
    )
    return {**state, "sql_query": sql, "sql_result": result, "trace": trace}
