"""
Pluggable LLM client.

Design note: the planning and insight-writing steps in this agent need a
language model. Rather than hard-coding one vendor, this module exposes a
single `LLMClient.complete()` call.

If `ANTHROPIC_API_KEY` is set in the environment, the module-level
`llm_client` singleton uses the real Anthropic Messages API. If it isn't,
a transparent, clearly-labeled rule-based fallback keeps the whole pipeline
runnable and testable without any API key.
"""

from __future__ import annotations

import json
import os
from typing import Optional

try:
    import httpx
except ImportError:
    httpx = None

DEFAULT_MODEL = "claude-sonnet-4-6"
ANTHROPIC_API_KEY: Optional[str] = os.environ.get("ANTHROPIC_API_KEY")


class LLMClient:
    """
    Thin wrapper so nodes never care which backend answers them.
    Constructed once per request with whatever credentials that request
    supplied — never a shared/global singleton, so one user's API key is
    never visible to, or reused for, another user's request.
    """

    def __init__(
        self, api_key: Optional[str] = None, model: Optional[str] = None
    ) -> None:
        self.api_key = api_key or ANTHROPIC_API_KEY or None
        self.model = model or DEFAULT_MODEL
        self.live = bool(self.api_key) and httpx is not None
        self.provider = "anthropic-live" if self.live else "rule-based-fallback"
        self.error: Optional[str] = None

    async def complete(
        self, system: str, user: str, *, json_mode: bool = False, max_tokens: int = 1000
    ) -> str:
        if self.live:
            try:
                return await self._live_complete(system, user, max_tokens=max_tokens)
            except Exception as e:
                # A bad/expired key, network issue, or rate limit shouldn't
                # crash the whole analysis — degrade to the rule-based path
                # for the rest of this client's calls and say so plainly.
                self.live = False
                self.provider = "rule-based-fallback"
                self.error = str(e)
                return self._fallback_complete(system, user, json_mode=json_mode)
        return self._fallback_complete(system, user, json_mode=json_mode)

    async def _live_complete(self, system: str, user: str, *, max_tokens: int) -> str:
        assert httpx is not None
        headers = {
            "x-api-key": self.api_key,
            "anthropic-version": "2023-06-01",
            "content-type": "application/json",
        }
        body = {
            "model": self.model,
            "max_tokens": max_tokens,
            "system": system,
            "messages": [{"role": "user", "content": user}],
        }
        async with httpx.AsyncClient(timeout=60) as client:
            resp = await client.post(
                "https://api.anthropic.com/v1/messages", headers=headers, json=body
            )
            resp.raise_for_status()
            data = resp.json()
            return "".join(
                block.get("text", "")
                for block in data.get("content", [])
                if block.get("type") == "text"
            )

    def _fallback_complete(self, system: str, user: str, *, json_mode: bool) -> str:
        """
        Deterministic, keyword-driven stand-in for an LLM call. It is NOT a
        real language model — it exists so the agent pipeline is genuinely
        runnable end-to-end without any API key. Every node that calls this
        degrades gracefully (simpler plan / templated prose) rather than
        silently faking a smarter result.
        """
        text = (system + " " + user).lower()

        if "classify the analytical intent" in system.lower():
            plan = {
                "needs_sql": True,
                "needs_stats": any(
                    k in text
                    for k in [
                        "correlat",
                        "significan",
                        "confidence",
                        "hypothesis",
                        "regress",
                    ]
                ),
                "needs_forecast": any(
                    k in text for k in ["forecast", "predict", "next", "trend"]
                ),
                "needs_segmentation": any(
                    k in text for k in ["segment", "cohort", "churn", "retention"]
                ),
                "intent": "general_analysis",
                "reasoning": "rule-based fallback: keyword match on the question (no API key supplied)",
            }
            return json.dumps(plan)

        if json_mode:
            return json.dumps(
                {"note": "fallback LLM: no API key supplied", "content": []}
            )

        if self.error:
            return (
                f"[Live Anthropic call failed ({self.error}) — degraded to the rule-based "
                "fallback for the rest of this analysis. Check your API key and try again.]"
            )
        return (
            "[Generated by rule-based fallback — no Anthropic API key was supplied for this "
            "request. Add one in the sidebar to enable live narrative generation.]"
        )


# Module-level singleton — used by nodes directly and patchable in tests.
llm_client: LLMClient = LLMClient()
